spring:
  data:
    redis:
      host: 192.168.183.136
      port: 6379
      username: poly
      password: 1234

    session:
      redis:
        flush-mode: on_save
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    open-in-view: false
  application:
    name: SpringSecurityPRJ
  datasource:
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    username: poly
    url: jdbc:mariadb://192.168.183.136:3306/myDB

jwt:
  token:
    creator: poly
    access:
      valid:
        time: 300
      name: jwtAccessToken
    refresh:
      valid:
        time: 3000
      name : jwtRefreshToken
  secret:
    key: '123456789123456789123456789123456789'

server:
  port: 11000